const Empdata = [
  {
    Name: "Gouranga Ghosh",
    Email: "Gourangabwn98@gmail.com",
    Address: "Burdwan,713101",
    Phone: "7797233633",
  },
  {
    Name: "Sumit das",
    Email: "sumit@gmail.om",
    Address: "Bagnan",
    Phone: "9867654365",
  },
  {
    Name: "Sneha Dutta",
    Email: "sn.du.sneha@gmail.com",
    Address: "Budbud",
    Phone: "6587986545",
  },
  {
    Name: "Rahul Roy",
    Email: "Rahul@gmail.com",
    Address: "Purba Burdwan",
    Phone: "7676765445",
  },
  {
    Name: "Malati Ghosh",
    Email: "Malati@gmail.com",
    Address: "Kalyani",
    Phone: "6556432345",
  },
  {
    Name: "Shyamal Ghosh",
    Email: "Shyamal23@gmail.com",
    Address: "Durgapur",
    Phone: "6556769878",
  },
  {
    Name: "Gouranga Ghosh",
    Email: "Gourangabwn98@gmail.com",
    Address: "Burdwan,713101",
    Phone: "7797233633",
  },
  {
    Name: "Sumit das",
    Email: "sumit@gmail.om",
    Address: "Bagnan",
    Phone: "9867654365",
  },
  {
    Name: "Sneha Dutta",
    Email: "sn.du.sneha@gmail.com",
    Address: "Budbud",
    Phone: "6587986545",
  },
  {
    Name: "Rahul Roy",
    Email: "Rahul@gmail.com",
    Address: "Purba Burdwan",
    Phone: "7676765445",
  },
  {
    Name: "Malati Ghosh",
    Email: "Malati@gmail.com",
    Address: "Kalyani",
    Phone: "6556432345",
  },
  {
    Name: "Shyamal Ghosh",
    Email: "Shyamal23@gmail.com",
    Address: "Durgapur",
    Phone: "6556769878",
  },
  {
    Name: "Gouranga Ghosh",
    Email: "Gourangabwn98@gmail.com",
    Address: "Burdwan,713101",
    Phone: "7797233633",
  },
  {
    Name: "Sumit das",
    Email: "sumit@gmail.om",
    Address: "Bagnan",
    Phone: "9867654365",
  },
  {
    Name: "Sneha Dutta",
    Email: "sn.du.sneha@gmail.com",
    Address: "Budbud",
    Phone: "6587986545",
  },
  {
    Name: "Rahul Roy",
    Email: "Rahul@gmail.com",
    Address: "Purba Burdwan",
    Phone: "7676765445",
  },
  {
    Name: "Malati Ghosh",
    Email: "Malati@gmail.com",
    Address: "Kalyani",
    Phone: "6556432345",
  },
  {
    Name: "Shyamal Ghosh",
    Email: "Shyamal23@gmail.com",
    Address: "Durgapur",
    Phone: "6556769878",
  },
  {
    Name: "Gouranga Ghosh",
    Email: "Gourangabwn98@gmail.com",
    Address: "Burdwan,713101",
    Phone: "7797233633",
  },
  {
    Name: "Sumit das",
    Email: "sumit@gmail.om",
    Address: "Bagnan",
    Phone: "9867654365",
  },
  {
    Name: "Sneha Dutta",
    Email: "sn.du.sneha@gmail.com",
    Address: "Budbud",
    Phone: "6587986545",
  },
  {
    Name: "Rahul Roy",
    Email: "Rahul@gmail.com",
    Address: "Purba Burdwan",
    Phone: "7676765445",
  },
  {
    Name: "Malati Ghosh",
    Email: "Malati@gmail.com",
    Address: "Kalyani",
    Phone: "6556432345",
  },
  {
    Name: "Shyamal Ghosh",
    Email: "Shyamal23@gmail.com",
    Address: "Durgapur",
    Phone: "6556769878",
  },
  {
    Name: "Gouranga Ghosh",
    Email: "Gourangabwn98@gmail.com",
    Address: "Burdwan,713101",
    Phone: "7797233633",
  },
  {
    Name: "Sumit das",
    Email: "sumit@gmail.om",
    Address: "Bagnan",
    Phone: "9867654365",
  },
  {
    Name: "Sneha Dutta",
    Email: "sn.du.sneha@gmail.com",
    Address: "Budbud",
    Phone: "6587986545",
  },
  {
    Name: "Rahul Roy",
    Email: "Rahul@gmail.com",
    Address: "Purba Burdwan",
    Phone: "7676765445",
  },
  {
    Name: "Malati Ghosh",
    Email: "Malati@gmail.com",
    Address: "Kalyani",
    Phone: "6556432345",
  },
  {
    Name: "Shyamal Ghosh",
    Email: "Shyamal23@gmail.com",
    Address: "Durgapur",
    Phone: "6556769878",
  },
];
export default Empdata;
